### PR TITLE
fix button border

### PR DESCRIPTION
**Pull request by aki-mizu**

### CODE REVIEW

**Comment by aki-mizu** [comment]
Hi, @yukibtc I'm new to the workflow for collaborators so I have some questions. 
Currently master branch is protected so I cannot commit directly to it, is it intended?
If so, am I supposed to work on a feature branch first then make a pull request for you to review for each change I make like this one?
Or am I supposed to continuously just work on a feature branch first and creating pull request only if major milestone has been reached?

**Comment by yukibtc** [comment]
Ah, I forgot to enable `Allow specified actors to bypass required pull requests`. I enabled it now. Let me know if you are able to push directly to `master` branch.

IMO, until the project is small (and you are the only one that directly work on it) or for small changes, push directly to `master` branch. For big changes, make a PR and eventually request a review.

**Comment by yukibtc** [comment]
I updated the contributing and code style, added `justfile` and some scripts to check that everything works (including the CI).

If is ok for you, I prefer to keep the same coding style, format and so on for all the `rust-nostr` projects.

**Comment by aki-mizu** [comment]
Thanks, I just pushed to `master` branch successfully.
Thank you for adding code style guidelines. It's a good idea to have uniformity, I will follow accordingly.

**Pull request merged**
